/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Sun May 28 00:02:23 2017. */

#include "MBMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ChangeSpeed_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ChangeSpeed, fan_speed, fan_speed, 0),
    PB_LAST_FIELD
};

const pb_field_t ChangeParams_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, ChangeParams, temperature, temperature, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, ChangeParams, humidity, temperature, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, ChangeParams, fan_speed, humidity, 0),
    PB_LAST_FIELD
};

const pb_field_t Commands_fields[2] = {
    PB_ONEOF_FIELD(cmd,   1, MESSAGE , ONEOF, STATIC  , FIRST, Commands, change_speed, change_speed, &ChangeSpeed_fields),
    PB_LAST_FIELD
};

const pb_field_t ExecResult_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, ExecResult, result, result, 0),
    PB_LAST_FIELD
};

const pb_field_t Responses_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Responses, on_command, on_command, 0),
    PB_ONEOF_FIELD(resp,   2, MESSAGE , ONEOF, STATIC  , OTHER, Responses, exec_result, on_command, &ExecResult_fields),
    PB_LAST_FIELD
};

const pb_field_t Notifications_fields[2] = {
    PB_ONEOF_FIELD(notif,   1, MESSAGE , ONEOF, STATIC  , FIRST, Notifications, change_parameters, change_parameters, &ChangeParams_fields),
    PB_LAST_FIELD
};

const pb_field_t MBMessage_fields[4] = {
    PB_ONEOF_FIELD(interface,   1, MESSAGE , ONEOF, STATIC  , FIRST, MBMessage, commands, commands, &Commands_fields),
    PB_ONEOF_FIELD(interface,   2, MESSAGE , ONEOF, STATIC  , FIRST, MBMessage, responses, responses, &Responses_fields),
    PB_ONEOF_FIELD(interface,   3, MESSAGE , ONEOF, STATIC  , FIRST, MBMessage, notifications, notifications, &Notifications_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Commands, cmd.change_speed) < 65536 && pb_membersize(Responses, resp.exec_result) < 65536 && pb_membersize(Notifications, notif.change_parameters) < 65536 && pb_membersize(MBMessage, interface.commands) < 65536 && pb_membersize(MBMessage, interface.responses) < 65536 && pb_membersize(MBMessage, interface.notifications) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ChangeSpeed_ChangeParams_Commands_ExecResult_Responses_Notifications_MBMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Commands, cmd.change_speed) < 256 && pb_membersize(Responses, resp.exec_result) < 256 && pb_membersize(Notifications, notif.change_parameters) < 256 && pb_membersize(MBMessage, interface.commands) < 256 && pb_membersize(MBMessage, interface.responses) < 256 && pb_membersize(MBMessage, interface.notifications) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ChangeSpeed_ChangeParams_Commands_ExecResult_Responses_Notifications_MBMessage)
#endif


/* @@protoc_insertion_point(eof) */
